services:
  postgres:
    image: postgres:18

    container_name: notes-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shantam
      POSTGRES_DB: notes

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .

    container_name: notes-api

    environment:
      DATABASE_URL: postgres://postgres:shantam@postgres:5432/notes?sslmode=disable
      JWT_SECRET: test

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
